### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by acrogenesis** [GoodLife/rails-patch-json-encode#4]
Is this gem still needed on Rails 4.2? The Rails issues have already been closed or merged

**Comment by lulalala** [comment]
To be honest that pull-request is quite large, so I really don't know. Would be good if someone who generates a lot of JSON can try it out and see if there are any performance improvements.

**Comment by acrogenesis** [comment]
I tried this gem (`rails-patch-json-encode`) with `oj` and didn't get significant speed up, but I did with oj_mimic_json`. I ran some benchmarks with a 10K+ item array of hashes  .to_json

**Comment by lulalala** [comment]
Just wondering, which of the setting did you choose to use?  `Rails::Patch::Json::Encode.patch_base_classes` or `Rails::Patch::Json::Encode.patch_renderers`?
`patch_base_classes` should have the same effect as `oj_mimic_json`.

**Comment by acrogenesis** [comment]
I don't remember setting a setting. Maybe that was my mistake

**Comment by lulalala** [comment]
Oh yeah can you call `Rails::Patch::Json::Encode.patch_base_classes` in an initializer? I really want to see how Rails 4 does before and after :D

**Comment by bquorning** [comment]
I’m seeing no difference on my Rails 4.1.12 application. I’m wondering if the issue wasn’t fixed by this merge https://github.com/rails/rails/commit/f7e4e37ae756e59da2e10bdeafd9458ef7189582 (PR https://github.com/rails/rails/pull/12183) which was released with Rails 4.1.0.

**Comment by lulalala** [comment]
@bquorning can you try the Rails::Patch::Json::Encode.patch_base_classes way and try again? And can you give a time comparison for prior and after? thanks.

**Comment by seanriordan08** [comment]
Loading development environment (Rails 4.0.13) (w/ gem 'rails-patch-json-encode')
[1] pry(main)> data = Hash.new
=> {}
[2] pry(main)> key = 'aaa'
=> "aaa"
[3] pry(main)> 1000.times { data[key.succ!] = data.keys }
=> 1000
[4] pry(main)> 1000 * Benchmark.realtime { data.to_json }
=> 585.7679999999999

Loading development environment (Rails 4.0.13)
[1] pry(main)> data = Hash.new
=> {}
[2] pry(main)> key = 'aaa'
=> "aaa"
[3] pry(main)> 1000.times { data[key.succ!] = data.keys }
=> 1000
[4] pry(main)> 1000 * Benchmark.realtime { data.to_json }
=> 2178.3070000000002

Loading development environment (Rails 4.2.0)
[1] pry(main)> data = Hash.new
=> {}
[2] pry(main)> key = 'aaa'
=> "aaa"
[3] pry(main)> 1000.times { data[key.succ!] = data.keys }
=> 1000
[4] pry(main)> 1000 * Benchmark.realtime { data.to_json }
=> 4060.6229999999996

**Comment by lulalala** [comment]
@seanriordan08 Thanks! Is the 4.2.0 result with the gem?

**Comment by seanriordan08** [comment]
Negative, the 4.2.0 results are without the gem. I am unable to get rails 4.2.0 to play nice with it in fact.

**Comment by seanriordan08** [comment]
As warned, I checked my tests and several no longer pass - could I get some tips on how to avoid the error below?

```
NameError:
       uninitialized constant Rails::Patch::Json::Encode::MultiJson
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/rails-patch-json-encode-0.1.1/lib/rails/patch/json/encode.rb:29:in `to_json'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/rendering.rb:16:in `render'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.0/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /Users/sriorda2/.rvm/gems/ruby-2.0.0-p643/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:40:in `render'

```

**Comment by lulalala** [comment]
@seanriordan08 If I remember correctly, Rails 4.2 removed multi_json dependency. You will have to add multi_json into your Gemfile. Your error is not able to find that class.

**Comment by lulalala** [comment]
So first, in Rails 4.2.6 console the result seems to be still there.
So here is my script:

```
require 'benchmark'
data = Hash.new
key = 'aaa'
1000.times { data[key.succ!] = data.keys }

Benchmark.bm do |x|
  x.report { 100.times do data.to_json; end }
end
```

P.S. @seanriordan08 you need to put the looping inside the benchmark block for it to be effective.


```
# without gem
       user     system      total        real
 147.070000   0.580000 147.650000 (148.095946)
```

```
# with gem / oj / patch_base_classes
       user     system      total        real
  19.770000   0.590000  20.360000 ( 20.375311)
```

@seanriordan08 I don't have more time right now. However can you try `require "multi_json"` on top of that controller first and see if it works?

**Comment by seanriordan08** [comment]
Indeed it seems to work :
```
w/o gem:
user     system      total        real
 211.970000   1.500000 213.470000 (214.407087)

w/ gem:
user     system      total        real
  30.560000   0.390000  30.950000 ( 31.140234)
```
Re-running the earlier benchmark, I get `305.486` instead of `4060.62`

I'm satisfied - to answer the issue title; "yes", when running rails 4.2.0, make sure you include multi_json in your gemfile:
```
gem 'rails', '4.2.0'
gem 'rails-patch-json-encode'
gem 'multi_json'
```

**Comment by seanriordan08** [comment]
Since rails 4.2.0 has the multi_json dependency, I was thrown off the troubleshooting path. I would love to know exactly why explicitly adding it to the gemfile solves the issue.

**Comment by lulalala** [comment]
After fixing #6, we found this gem still can speed up Rails 5.

However if you are using oj, you don't need to use this gem. I added a note in the readme.

Sorry for the lack of action by me here.
