### ISSUE TITLE
Warning: This gem may be harming performance in rails 5+ apps

### ISSUE THREAD

**Issue by simonista** [GoodLife/rails-patch-json-encode#6]
In rails 5, rails to_json monkey patch [switched from an `alias_method_chain` to a `Module#prepend`](https://github.com/rails/rails/commit/d5bddc1b2d3d794b2eddcb7309f41f87a8d665c1#diff-cc70a442885bd6fb06e762c71810eebc) which means that `rails-patch-json-encode` is now _above_ the core rails monkeypatch in the call hierarchy.  This essentially means that we're taking on all the rails overhead, and then throwing it away and doing all the `as_json` work again in the context of `MultiJson`.

This is mitigated if you are also using `Oj` as the [rails encoder](https://github.com/ohler55/oj/blob/master/pages/Rails.md), which combined with the above `prepend` change means that the `rails-patch-json-encode` base class patches are bypassed entirely.

Benchmark:

```ruby
#!/usr/bin/env ruby

require 'benchmark'
require 'json'
require 'byebug'

def profile
  blob = File.read(File.join('zips.json'))
  time = Benchmark.realtime do
    JSON.parse(JSON.parse(blob).to_json).to_json
  end
  time * 1000
end

NUM = 10

puts NUM.times.map { profile }.reduce(:+)/NUM.to_f

require 'active_support/json'
require 'active_support/core_ext/object/json'

puts NUM.times.map { profile }.reduce(:+)/NUM.to_f

require 'multi_json'
require 'oj'
require 'rails/patch/json/encode'
Rails::Patch::Json::Encode.patch_base_classes

puts NUM.times.map { profile }.reduce(:+)/NUM.to_f

Oj.optimize_rails()

puts NUM.times.map { profile }.reduce(:+)/NUM.to_f
```

gives this output on my macbook pro:

```bash
509.81919998303056
2271.942200011108
3755.3071999922395
288.06960000656545
```

Notes:
- tested with `rails-patch-json-encode-0.1.1`, `activesupport-5.1.4`, `json-2.1.0`, `multi_json-1.12.2`, `oj-3.3.9`
- json file used to test was from http://jsonstudio.com/resources, slightly modified to parse as a single json doc)

**Comment by lulalala** [comment]
@simonista thanks for this detailed report! I just ported recent Rails/Ruby changes and made a fix. Could you email me the json test file you use? mark@goodlife.tw

**Comment by simonista** [comment]
Sheesh, I can't believe that site that was hosting the large json file is gone.  Here is is: https://gist.githubusercontent.com/simonista/0c09188c55356b2baa89f90d04644228/raw/17a832a078b7eab04ecebac33428835edd70b501/zips.json

**Comment by lulalala** [comment]
I just tested it on the prepend branch. Now it properly speeds up the encoding process now. My testing showed 1/7 of time taken. Thank you very much.

Can you test on your site and see if it works? If all things are well, I'll release a new version.

**Comment by simonista** [comment]
Yeah, this fixes the issue I'm was seeing.  Running the same script again I get better numbers for `rails-patch-json-encode`, although it shouldn't be used with `Oj.optimize_rails()` because it makes that worse:

```
550.7778000319377
2401.5816000057384
816.1468000384048
689.2391999950632
```

I still think it may be worth encouraging people to use `Oj.optimize_rails()` if they can, as that seems to be the most performant solution, although obviously it's a native extension so it won't work for everyone.

Personally, we're going to use that solution (although we appreciate the work you did here! Just feel it's no longer necessary for us)

**Comment by lulalala** [comment]
Cool thanks. Sure I guess this gem may still has some use for people using Jruby.

**Comment by lulalala** [comment]
Change pushed to master branch and 0.2.0 gem is released.
